### ISSUE TITLE
[FEATURE] adjust vscode settings

### ISSUE THREAD

**Issue by zoosmand** [BstLabs/py-clvm#133]
**Is your feature request related to a problem? Please describe.**
To work properly with MFA, vscode settings have to be adjusted 

```
"remote.SSH.showLoginTerminal": true,
"remote.SSH.useLocalServer": false,
"remote.SSH.connectTimeout": 120,
```
to add new command "adjust" to vscode block of commands

```
clvm vscode adjust
```
Settings file location depends on the OS.
https://stackoverflow.com/questions/65908987/how-can-i-open-visual-studio-codes-settings-json-file

**Comment by zoosmand** [comment]
Take into account that "clvm vscode install" should adjusted the settings as well.

**Comment by ShahriyarR** [comment]
For Linux the path is:
`~/.config/Code/User/settings.json`

But it stores all settings and that means it should be edited directly.
The better way is to figure out how to supply extra settings or the only possible solution is to edit this file and add.

**Comment by ShahriyarR** [comment]
Another possible solution is to write VsCode extension and use it, but it requires some more time.
