### ISSUE TITLE
add public ip address to instance ls command output table

### ISSUE THREAD

**Issue by radubonteanunatac** [BstLabs/py-clvm#182]

**Comment by asterkin** [comment]
Normally, clvm communicates with VM instances over protectec channel (e.g. AWS SSM or special SSH basttion) and therefore does not assume any public IPs whatsoever. In fact, our VMs do not have public IP at all. I could imagine that printing public Ip, if such defined, in clvm instance ls output, could be used to spot violations of this rule. Is this is what you keep in your mind, or it's something else?
