### ISSUE TITLE
[BUG] clvm vscode start <instance name> does not start instance

### ISSUE THREAD

**Issue by asterkin** [BstLabs/py-clvm#71]
**Describe the bug**
if the instance is stopped the ssh connect will fail

**To Reproduce**
Steps to reproduce the behaviour: (fix typo in template)
clvm vscode start <your-instance-name>

**Expected behaviour** (fix typo in template)
should start the instance if it's down

**Screenshots**

**Extra info:**
 - OS: [e.g. Amazon Linux 2]
 - Affected Version
 - One could argue that ssh will start the instance, but due to the robustness problem it will fail anyhow.

**Comment by ShahriyarR** [comment]
Closing. Implemented.
