### ISSUE TITLE
[BUG] Invalid handling of ssh new for new instance with the same name

### ISSUE THREAD

**Issue by asterkin** [BstLabs/py-clvm#72]
**Describe the bug**
Seems like old instance id is stored somewhere, plus known_hosts gets a conflict

**To Reproduce**
Steps to reproduce the behaviour: (fix the template)
1. Create an instance, invoke clvm ssh new
2. Shutdown instance
3. Create a new one with the same name
4. Try ssh new - observe error message

**Expected behaviour** (fix the template)
Should allow creating new ssh key for new instance with the same name

**Screenshots**

**Extra info:**
 - OS: [e.g. Amazon Linux 2]
 - Affected Version

**Comment by asterkin** [comment]
To remove from known_hosts, use
ssh-keygen -f "/home/asher/.ssh/known_hosts" -R "caios-dev-asher-arm64-desktop"

**Comment by ShahriyarR** [comment]
Related to #116

**Comment by zoosmand** [comment]
Not relevant
