### ISSUE TITLE
[BUG] Incorrect handling terminated instances

### ISSUE THREAD

**Issue by asterkin** [BstLabs/py-clvm#79]
**Describe the bug**
If there is a terminated instance with the same name some operations (e.g. connect) might pick it up instead of a new running one.

**To Reproduce**
Steps to reproduce the behavior: (fix typo in template)
Create an instance (e.g. via stack) with particular name
Terminate this instance (e.g. delete the stack)
Create an instance with the same name (e.g. launch new stack)
Try to connect

**Expected behavior** (fix the template)
It should connect to running instance rather than to terminated one

**Screenshots**
![image](https://user-images.githubusercontent.com/6297664/168473470-ea052660-f424-4796-b74d-6ac775a94f6a.png)

**Extra info:**
 - OS: [e.g. Amazon Linux 2]
 - Affected Version

**Comment by asterkin** [comment]
It should probably go deeper to vm instances library

**Comment by ShahriyarR** [comment]
Closing. Implemented in new versions.
