### ISSUE TITLE
[BUG] Cannot change delay or retry parameters in ssm shell

### ISSUE THREAD

**Issue by asterkin** [BstLabs/py-clvm#80]
**Describe the bug**
They are treated as str while should be int

**To Reproduce**
Steps to reproduce the behavior: (fix the template)
clvm ssm shell ls / delay=10

**Expected behavior** (fix the typo)
should not fail

**Screenshots**

**Extra info:**
 - OS: [e.g. Amazon Linux 2]
 - Affected Version

**Comment by asterkin** [comment]
The problem should probably solved at the dynacli level. Indeed,in python when we pass **kwargs it correctly recognises integers vs strings, etc.

**Comment by ShahriyarR** [comment]
Closing. Implemented.
