### ISSUE TITLE
[BUG] Port mapping is not functioning as expected

### ISSUE THREAD

**Issue by orkhanshirin** [BstLabs/py-clvm#83]
**Describe the bug**
It's supposed to pick and unpack specific params from kwargs. However the handling of kwargs items is not implemented correctly and the function returns default values only.

**To Reproduce**
`clvm redirect start <instance_name> port=8181(or any port number)`

The code-server will be available only at `localhost:8080/`

**Expected behavior**
It's expected to take the `port` argument into consideration and redirect my code-server to port 8181(or any other port)

**Screenshots**

**Extra info:**
 - OS: [Linux Ubuntu]
 - Affected Version:  20.04 LTS

**Comment by ShahriyarR** [comment]
@orkhanshirin did you manage to nail down the core of the issue?

**Comment by ShahriyarR** [comment]
@orkhanshirin what is the final decision?

**Comment by orkhanshirin** [comment]
> @orkhanshirin what is the final decision?

It's in progress now. Apparently, we can pass the port numbers like  `8080=9090`. We need a more intuitive implementation.
