### ISSUE TITLE
[BUG] clvm instance connect gets stuck

### ISSUE THREAD

**Issue by lkashti** [BstLabs/py-clvm#90]
**Describe the bug**
when using 'clvm instance connect <instance-name>'
it gets stuck like in the following screenshot
It worked for me by locally reverting commit 5fa84e8192b66adedcd927492b1c1e496fc062ae, it could be related

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48313697/170871201-f0869f8b-a4ee-4384-a69d-6c5791613ba1.png)

**Extra info:**
 - OS: [e.g. Amazon Linux 2]
 - Affected Version

**Comment by lkashti** [comment]
looks like other ssm related features are affected as well

**Comment by ShahriyarR** [comment]
@orkhanshirin please revert the changes accordingly.
