### ISSUE TITLE
[BUG] clvm instance stop prints irrelevant message

### ISSUE THREAD

**Issue by asterkin** [BstLabs/py-clvm#95]
**Describe the bug**
First, it takes more time than before. Second, it prints irrelevant message at the end.

**To Reproduce**
clvm instance stop <instance-name>

**Expected behavior**
No extra message

**Screenshots**
asterkin@asterkin-ideacentre-AIO-510-23ISH ~ $ clvm instance stop caios-dev-asher-x86-64-desktop caios-dev-asher-arm64-desktop
Enter MFA Code: 882122
Stopping caios-dev-asher-x86-64-desktop ...
Stopping caios-dev-asher-arm64-desktop ...
caios-dev-asher-x86-64-desktop stopped.
caios-dev-asher-arm64-desktop stopped.
[None, None]

**Extra info:**
 - OS: [e.g. Amazon Linux 2]
 - Affected Version

**Comment by ShahriyarR** [comment]
Already fixed.
